
SPLIT=b'\x00\x00\x00\x00'
PROACTIVE='proactive'
PASSIVE='passive'

CLK=1

# PING=b'/ping'
# PONG=b'pong'
# FAIL=b'failed'
# RECV=b'received'

GOOD=0

ERROR_PATH_NOT_FOUND=-1
ERROR_NEED_ADDRESS=-2
ERROR_LOAD_PUBLIC_KEY=-3
ERROR_404=-4

CLIENT_SEND_BROKEN=-10
CLIENT_RECV_BROKEN=-11
CLIENT_RECV_BAD_KEY=-12
CLIENT_CHECKSUM_FAILURE=-13

SERVER_SEND_BROKEN=-20
SERVER_RECV_BROKEN=-21
SERVER_WTF=-22
SERVER_WRONG_NAME=-23
SERVER_STRANGE_USER=-24
SERVER_DECRYPT=-25

IP_ADDRESS_SPOOFING=-30
